//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSocialHerb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public string ArticleID { get; set; }
        public string ArticleName { get; set; }
        public string Article1 { get; set; }
        public string ArticleReference { get; set; }
        public string ArticleImage { get; set; }
    }
}
