//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSocialHerb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class socialherbdbEntities1 : DbContext
    {
        public socialherbdbEntities1()
            : base("name=socialherbdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<disease> disease { get; set; }
        public virtual DbSet<herb> herb { get; set; }
        public virtual DbSet<herbdetail> herbdetail { get; set; }
        public virtual DbSet<infographic> infographic { get; set; }
    }
}
