//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSocialHerb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disease
    {
        public string DiseaseID { get; set; }
        public string DiseaseName { get; set; }
        public string Syntom { get; set; }
        public string Herb { get; set; }
    }
}
