//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSocialHerb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class herb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public herb()
        {
            this.herbdetail = new HashSet<herbdetail>();
        }
    
        public string HerbName { get; set; }
        public string NameOther { get; set; }
        public string HerbImg { get; set; }
        public string Leaf { get; set; }
        public string LeafImg { get; set; }
        public string Trunk { get; set; }
        public string TrunkImg { get; set; }
        public string Root { get; set; }
        public string RootImg { get; set; }
        public string Crop { get; set; }
        public string CropImg { get; set; }
        public string Corm { get; set; }
        public string CormImg { get; set; }
        public string Flower { get; set; }
        public string FlowerImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<herbdetail> herbdetail { get; set; }
    }
}
