//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSocialHerb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class herbdetail
    {
        public string DetailID { get; set; }
        public string HerbName { get; set; }
        public string Properties { get; set; }
        public string Help { get; set; }
        public string Warning { get; set; }
        public string ResearchName { get; set; }
        public string Research { get; set; }
        public string Author { get; set; }
        public string Link { get; set; }
    
        public virtual herb herb { get; set; }
    }
}
